# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/FastRequest',
                'doc_host': 'https://tripathysagar.github.io',
                'git_url': 'https://github.com/tripathysagar/FastRequest',
                'lib_path': 'FastRequest'},
  'syms': {'FastRequest.core': {'FastRequest.core.foo': ('core.html#foo', 'FastRequest/core.py')}}}
